ARG BASE_REGISTRY=172.73.0.156:85
FROM ${BASE_REGISTRY}/python:3.13-slim
WORKDIR /app

ARG PYPI_MIRROR=https://pypi.org/simple

# 复制后端代码
COPY backend/pyproject.toml ./
COPY backend/app/ ./app/
COPY backend/main.py ./

# 安装依赖
RUN pip install --no-cache-dir --progress-bar off -i ${PYPI_MIRROR} hatchling && \
    pip install --no-cache-dir --progress-bar off -i ${PYPI_MIRROR} --no-build-isolation .

EXPOSE 8000
CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
