ARG BASE_REGISTRY=172.73.0.156:85
FROM ${BASE_REGISTRY}/nginx:1.27-alpine

# 本地已执行 npm run build，直接复制构建产物
COPY frontend/dist /usr/share/nginx/html
COPY deploy/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
