"""Parse AgenticOS theme CSS files and resolve ``var(--token)`` references in SVG.

Each theme CSS file (36 total) defines a ``:root { }`` block with CSS custom
properties.  This module extracts those tokens and provides deterministic
string replacement so the AI can generate SVG with ``var(--bg)`` etc. while
the stored artifact contains self-contained hex values.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

logger = logging.getLogger("ppt_artifact.token_resolver")

# Directory containing the design-system-derived PPT theme CSS files
# Generated by backend/scripts/convert_design_systems.py from data/design-systems/
from app.core.data_path import DESIGN_THEMES_DIR
_THEMES_DIR = DESIGN_THEMES_DIR

# Cache: theme_name → {--token_name: value}
_token_cache: dict[str, dict[str, str]] = {}

# Regex to pick out custom property declarations inside the :root block
_ROOT_BLOCK_RE = re.compile(r":root\s*\{([^}]+)\}", re.DOTALL)
_TOKEN_RE = re.compile(r"--([\w-]+)\s*:\s*([^;]+);")


def parse_theme_css(css_text: str) -> dict[str, str]:
    """Extract all ``--name: value`` pairs from the ``:root { }`` block."""
    tokens: dict[str, str] = {}
    m = _ROOT_BLOCK_RE.search(css_text)
    if m is None:
        return tokens
    block = m.group(1)
    for match in _TOKEN_RE.finditer(block):
        name = f"--{match.group(1)}"
        value = match.group(2).strip()
        tokens[name] = value
    return tokens


def load_theme_tokens(theme_name: str) -> dict[str, str]:
    """Load and cache token dictionary for *theme_name*.

    Returns an empty dict when the theme file doesn't exist.
    """
    if theme_name in _token_cache:
        return _token_cache[theme_name]

    css_path = _THEMES_DIR / f"{theme_name}.css"
    if not css_path.is_file():
        logger.warning("Theme CSS not found: %s", css_path)
        _token_cache[theme_name] = {}
        return {}

    tokens = parse_theme_css(css_path.read_text(encoding="utf-8"))
    _token_cache[theme_name] = tokens
    return tokens


def resolve_token_values(svg_content: str, tokens: dict[str, str]) -> str:
    """Replace every ``var(--token_name)`` in *svg_content* with its resolved value."""
    result = svg_content
    unresolved: list[str] = []
    for token_name, value in tokens.items():
        if not value:
            continue
        placeholder = f"var({token_name})"
        result = result.replace(placeholder, value)
    # Warn if any var() references remain unresolved (theme mismatch / invalid theme)
    remaining = re.findall(r"var\(--[\w-]+\)", result)
    if remaining:
        logger.warning(
            "Unresolved var() references remain in SVG: %s. "
            "Theme tokens may be missing or theme name is invalid. "
            "Consider using a valid theme like 'apple' as fallback.",
            sorted(set(remaining)),
        )
    return result


# Tokens that represent colors (as opposed to radii, shadows, fonts, etc.)
_COLOR_TOKEN_NAMES = {
    "--bg", "--bg-soft", "--surface", "--surface-2",
    "--border", "--border-strong",
    "--text-1", "--text-2", "--text-3",
    "--accent", "--accent-2", "--accent-3",
    "--good", "--warn", "--bad",
    "--grad", "--grad-soft",
}

# Tokens that can be resolved with string replacement (colors + gradients + fonts)
_RESOLVABLE_TOKEN_NAMES = _COLOR_TOKEN_NAMES | {
    "--font-sans", "--font-display", "--font-mono", "--font-serif",
}


def build_color_token_table(theme_name: str) -> str:
    """Build a compact Markdown table of tokens for *theme_name*.

    Includes color tokens and font tokens (radius/shadow tokens are
    skipped because they are not valid SVG attribute values).
    """
    tokens = load_theme_tokens(theme_name)
    if not tokens:
        return f"(Theme '{theme_name}' not found)\n"

    lines = ["| Token | Value |", "|-------|-------|"]
    for name in sorted(tokens):
        if name not in _RESOLVABLE_TOKEN_NAMES:
            continue
        lines.append(f"| {name} | {tokens[name]} |")
    return "\n".join(lines)


def build_token_quick_ref() -> str:
    """Return a compact semantic reference for every CSS token the AI may use."""
    return """**Token 语义速查**（颜色用 `var(--xxx)` 引用，数值直接从下表取值）：
| Token | 用途 | 用法 |
|-------|------|------|
| --bg | 幻灯片背景 | `fill="var(--bg)"` |
| --bg-soft | 柔化背景（浅遮罩） | `fill="var(--bg-soft)"` |
| --surface / --surface-2 | 卡片/面板背景 | `fill="var(--surface)"` |
| --text-1 / --text-2 / --text-3 | 一级/二级/三级文字 | `fill="var(--text-1)"` |
| --accent / --accent-2 / --accent-3 | 强调/品牌色 | `fill="var(--accent)"` |
| --good / --warn / --bad | 正向/警告/负面语义色 | `fill="var(--good)"` |
| --border / --border-strong | 边框/分割线 | `stroke="var(--border)"` |

**字体 Token**（在 font-family 中使用 var() 引用，后端自动解析）：
| Token | 默认值 |
|-------|--------|
| --font-sans | Inter, Noto Sans SC, sans-serif |
| --font-serif | Playfair Display, Noto Serif SC, serif |
| --font-display | 展示字体（封面/标题用） |
| --font-mono | JetBrains Mono, monospace |

用法：`font-family="var(--font-sans)"` — 封面标题用 `var(--font-display)`，正文用 `var(--font-sans)`，代码用 `var(--font-mono)`。

**非颜色 Token**（直接取值使用，不用 var() 语法）：
| Token | 默认值 | SVG 用法 |
|-------|--------|---------|
| --radius: 12px | 卡片圆角 | `rx="12"` |
| --radius-sm: 8px | 小圆角 | `rx="8"` |
| --radius-lg: 20px | 大圆角 | `rx="20"` |
| --shadow | 参考值 | SVG `<filter><feDropShadow...>`，不用 CSS 值 |
| --shadow-lg | 参考值 |同上 |

**重要**：radius、shadow 等非颜色属性**不要使用 var() 语法**，直接在 SVG 属性中写数值。font-family 可以使用 var() 引用字体 token。"""


def list_available_themes() -> list[str]:
    """Return sorted list of theme names found on disk."""
    themes_dir = _THEMES_DIR
    if not themes_dir.is_dir():
        # Fallback: resolve from project root
        fallback = Path(__file__).resolve().parents[3] / "data" / "design-themes"
        if fallback.is_dir():
            themes_dir = fallback
        else:
            return []
    return sorted(p.stem for p in themes_dir.glob("*.css"))
